// <auto-generated />
using System;
using GroceryDisplay.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GroceryDisplay.Api.Migrations
{
    [DbContext(typeof(GroceryDbContext))]
    [Migration("20260719230413_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("grocery")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroceryDisplay.Api.Data.Entities.Person", b =>
                {
                    b.Property<string>("PersonId")
                        .HasMaxLength(32)
                        .HasColumnType("text")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<short>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PersonId")
                        .HasName("pk_person");

                    b.ToTable("person", "grocery", t =>
                        {
                            t.HasCheckConstraint("ck_person_id_format", "person_id ~ '^[a-z][a-z0-9_-]{1,31}$'");
                        });
                });

            modelBuilder.Entity("GroceryDisplay.Api.Data.Entities.Receipt", b =>
                {
                    b.Property<long>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("receipt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("ReceiptId"));

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("amount_cents");

                    b.Property<string>("ClientEntryId")
                        .HasMaxLength(64)
                        .HasColumnType("text")
                        .HasColumnName("client_entry_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("api")
                        .HasColumnName("created_by");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("text")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("PurchasedOn")
                        .HasColumnType("date")
                        .HasColumnName("purchased_on");

                    b.Property<string>("StoreName")
                        .HasColumnType("text")
                        .HasColumnName("store_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("VoidReason")
                        .HasColumnType("text")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<string>("VoidedBy")
                        .HasColumnType("text")
                        .HasColumnName("voided_by");

                    b.HasKey("ReceiptId")
                        .HasName("pk_receipt");

                    b.HasIndex("ClientEntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_receipt_client_entry_id");

                    b.HasIndex("PurchasedOn")
                        .HasDatabaseName("ix_receipt_purchased_on");

                    b.HasIndex("PersonId", "PurchasedOn")
                        .HasDatabaseName("ix_receipt_person_purchased_on");

                    b.HasIndex("PurchasedOn", "PersonId")
                        .HasDatabaseName("ix_receipt_active_year_lookup")
                        .HasFilter("voided_at is null");

                    b.ToTable("receipt", "grocery", t =>
                        {
                            t.HasCheckConstraint("ck_receipt_amount_cents_positive", "amount_cents >= 0");

                            t.HasCheckConstraint("ck_receipt_void_consistency", "(\r\n    voided_at is null\r\n    and voided_by is null\r\n    and void_reason is null\r\n)\r\nor\r\n(\r\n    voided_at is not null\r\n    and voided_by is not null\r\n    and void_reason is not null\r\n)");
                        });
                });

            modelBuilder.Entity("GroceryDisplay.Api.Data.Entities.Receipt", b =>
                {
                    b.HasOne("GroceryDisplay.Api.Data.Entities.Person", "Person")
                        .WithMany("Receipts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receipt_person_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GroceryDisplay.Api.Data.Entities.Person", b =>
                {
                    b.Navigation("Receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
